name: Linting
on: [push, pull_request]
jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jamescurtin/isort-action@master
        with:
            configuration: --check-only
